- qiskit_algorithms/optimizers/adam_amsgrad.py
- qiskit_algorithms/optimizers/spsa.py
- qiskit_algorithms/phase_estimators/phase_estimation_result.py
- test/optimizers/test_spsa.py
> Remove deprecated logic from algorithms

- qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
- qiskit_algorithms/optimizers/snobfit.py
- qiskit_algorithms/time_evolvers/pvqd/pvqd.py
- releasenotes/notes/change_exception-85f9f8d86ac16720.yaml
- test/time_evolvers/test_pvqd.py
In a couple of places `QiskitError` was directly raised. Normally the algorithms raise an `AlgorithmError` so given algorithms has been moved out of Qiskit, to better distinguish the exception to algorithms, and to make it consistent with elsewhere I changed the couple of places to raise AlgorithmError instead.
Resolves #30 
As AlgorithmError extends QiskitError its unlikely that this has any impact on anyone. I added a release note in case. Indeed the `test_pvqd` unit test, that checked an error condition continued to work unchanged - though I did change it to AlgorithmError as that is really what should be expected now.
Of course I ran tests, and built html locally and it was all good.... such a small change.... I did not run lint!
```
tools/check_copyright.py:1:0: R0401: Cyclic import …
```
> Replace raising QiskitError by AlgorithmError

- qiskit_algorithms/eigensolvers/numpy_eigensolver.py
- qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
- qiskit_algorithms/minimum_eigensolvers/qaoa.py
- qiskit_algorithms/optimizers/aqgd.py
- qiskit_algorithms/optimizers/p_bfgs.py
- qiskit_algorithms/optimizers/scipy_optimizer.py
- qiskit_algorithms/utils/validation.py
- test/test_validation.py
Resolves #32
This makes a local copy of the qiskit.utils validation.py and updates the code to use this. The test case is also switched to test this local instance not the one in Qiskit!
Since that file is only used by algorithms to raise errors, in a way that's consistent if these functions are used, and its all internal no release note is needed as there is no user facing change - a ValueError will still be raised as stated.
> Utilize local instance of validation.py

- qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
- releasenotes/notes/remove-deprecated-threshold-adaptvqe-7f862fe4b9b677d0.yaml
- test/minimum_eigensolvers/test_adapt_vqe.py
Fixes #37.
I think that the removal of this argument is justified with the move to a new repository, the deprecation warning refers to `qiskit-terra` versions and can be confusing (particularly after the repo rename). And even though the previously emitted warning was "pending deprecation", I think that most users don't really tell apart a deprecation from a pending deprecation, and the alternative path has been laid out for long enough for users to be able to easily transition to the new argument.
> Remove `threshold` argument from AdaptVQE

- qiskit_algorithms/minimum_eigensolvers/qaoa.py
- qiskit_algorithms/minimum_eigensolvers/sampling_vqe.py
Fixes #48 
Removes the text that claimed in one place for the callback it included best measurement.
Also tweaked text in a couple of places so it says `an Optimizer` rather than `a Qiskit Optimizer`
> Remove best measurement text - fixes #48

- docs/apidocs/qiskit_algorithms.time_evolvers.trotterization.rst
- qiskit_algorithms/__init__.py
- qiskit_algorithms/time_evolvers/trotterization/__init__.py
- qiskit_algorithms/time_evolvers/trotterization/trotter_qrte.py
- test/time_evolvers/test_trotter_qrte.py
While we allowed the new VQE etc to be imported from qiskit_algorithms the new TrotterQRTE was overlooked. It can now be imported from qiskit_algorithms so you do not need to import it from the sub-module, but that still works for any code that does. 
Updated the docs so TrotterQRTE is documented  at that level along with the other algorithms. Also made a couple of highlighted and plain text items class refs to the content so they become links.
Also the docstring stated the default was LieTrotter with reps=1 but was relying on the default value in LieTrotter being 1 to make this so. I set it explicitly just in case the default in the constructor ever gets changed.
> Short import for TrotterQRTE

- qiskit_algorithms/minimum_eigensolvers/sampling_mes.py
- releasenotes/notes/update_sampling_result-6f65d2c54d7a88c3.yaml
Fixes #58.
Simply removes the overriden `__str__` method in the sampling result class so conversion to string is done by the parent AlgorithmResult (as it done for all other results so it makes things consistent too).
Longer terms the change proposed in #53 will change things up by using dataclass so the result string format is wanted to be improved, maybe include a capability for just including the common fields or whatever things can be revisited at that point.
Was 
```
>>> res = SamplingVQEResult()
>>> print(res)
SamplingMinimumEigensolverResult:
Eigenvalue: None
Best measurement
: None
```
Now
```
>>> res = SamplingVQEResult()
>>> print(res)
{   'aux_operators_evaluated': None,
'best_measurement': None,
'cost_function_evals': None,
'eigenstate': None,
'eigenvalue': None, …
```
> Fix result print for SamplingVQE & QAOA - fixes #58

- test/optimizers/test_optimizers_scikitquant.py
Fix the numpy version check in the test suite to account for the possibility that `numpy.__version__` may contain letters.
Prior to this change, running tests on numpy 1.26.0b1 would result in the following error:
```
test/python/algorithms/optimizers/test_optimizers_scikitquant.py:72: in TestOptimizers
tuple(map(int, numpy.__version__.split("."))) >= (1, 24, 0),
E   ValueError: invalid literal for int() with base 10: '0b1'
```
Since the third component is matched against zero, the simplest solution is to check only the first two components, since we can expect that the first two split elements will be integers.
This is synced from the equivalent qiskit change:
https://github.com/Qiskit/qiskit/pull/10723
> Fix test suite to account for beta numpy versions

- .pylintdict
- qiskit_algorithms/py.typed
- releasenotes/notes/remove-typing-marker-2b1684ceb542b51a.yaml
Even though `qiskit-algorithms` included a `py.typed` marker, reporting
itself as being typed, the types were not checked and contained many errors.
This will be fixed in the 0.3 release (see #73) but I suggest that we release a
bugfix release in an untyped form to allow dependent packages that are
themselves typed to continue type checking normally.
> [stable] Remove `py.typed`

- qiskit_algorithms/__init__.py
`VarQite` and `VarQrte` return a `VarQTETResult` but it was missing from the API ref. I added it so the result return from the `evolve` methods now can correctly link to this the result.
I marked it for backport as we can re-publish the docs so as to update them to include this.
> VarQTEResult missing from API ref.

- constraints.txt
- qiskit_algorithms/optimizers/snobfit.py
- qiskit_algorithms/optimizers/spsa.py
Closes #10
This removes the numpy constraints to < 1.25. The failure noted in #10 was the treatment of deprecation warnings as errors by the test base class brought over when the code was migrated here. That base class was changed. Deprecation warnings are now simply collected by CI and should be remedied, if caused by qiskit-algorithms code, by do not cause errors especially if these are emitted by 3rd party libraries. Running `test_imfil` indeed causes some deprecation messages to be emitted but code still works for now and passes the unit test.
```
.../SQImFil/_history.py:27: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy …
```
> Remove numpy 1.25 constraint

- test/minimum_eigensolvers/test_vqe.py
I noticed that the VQE instance in a unit test seemed to be passed an estimator twice. The latter parameter named estimator was however an optimizer from the ddt data. Given it's confusing I changed the parameter name as well as the test case name which maybe more what it was in the past but is rather out of date now/
> Improve unit test

- qiskit_algorithms/eigensolvers/vqd.py
- qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
- qiskit_algorithms/minimum_eigensolvers/qaoa.py
- qiskit_algorithms/minimum_eigensolvers/sampling_vqe.py
- qiskit_algorithms/minimum_eigensolvers/vqe.py
- qiskit_algorithms/utils/validate_initial_point.py
CI is failing here with the latest mypy (1.6.0). The issue seems to be around override in initial_point setter/getter.
In looking the base class defines the type as an optional numpy array. Yet we change things up to Sequence[float] in derived classes and then have to ignore the arg to minimize/optimize as that takes a POINT (union of numpy array or float). Given the initial point needs to line up with what is passed to optimizer, and scipy mimimize states it takes a numpy array (although internally it does as asarray() on whats passed) I have changed the type hints all over to np.ndarray from Sequence. QAOA initial_point was already a numpy array and that had an ignore in order to call the parent SamplingVQE that takes a Sequence.
As such I felt this was clearer/cleaner. People pass …
> Fix Ci for latest mypy

- qiskit_algorithms/optimizers/gsls.py
- releasenotes/notes/fix_gsls_bounds-29d4a7506130cd69.yaml
- test/optimizers/test_optimizers.py
Fixes #94
When the optimizer creates its upper and lower bound arrays, any None entrys are replaced by infinity (i.e. No bound)
> Fix GSLS optimizer bounds if entries have None

- qiskit_algorithms/state_fidelities/base_state_fidelity.py
- releasenotes/notes/fix_fidelity_cache-3a4cc328344716e0.yaml
Fixes #90
Switches from `id()` to `_circuit_key()` where the latter is that which the reference primitives use. Using id() is problematic, as #90 notes, though `_circuit_key` is designated a private method, and while its the better choice functionally, it feels a bit off to be using what is designated a private method. Its been used/stable for a while though. A choice might be to copy the whole routine here - but perhaps better to see if this changes going forwards in the way some unique key/hash can be obtained for a circuit.
> Fix State Fidelity cache key

- test/time_evolvers/test_trotter_qrte.py
QDrift is now independently seeded in Qiskit 0.45. It used to be seeded from algorithms_globals but with that being deprecated from Qiskit, and moved here, the RNG and seed it used had to change. This changes the failing test to directly seed QDrift rather than do it via algorithm_globals as had been done before. This makes that test dependent on the latest Qiskit though - I think this is ok though.
> Fix CI failure with Qiskit 0.45 - Trotter QDrift test

- qiskit_algorithms/state_fidelities/base_state_fidelity.py
- qiskit_algorithms/state_fidelities/compute_uncompute.py
- releasenotes/notes/fix-fidelity-00fbfa9919e860de.yaml
Fixes #91
I changed the logic so that the `sampler.run` is done in the main thread and the resulting job and result is processed for the fidelity result in a separate method that is run by the thread executor of the algorithm job. This new method (_call which I named to be the same as the ref. primitives) gets passed all it needs as params, self is not passed, and where that logic was using some private instance utility methods I turned these to static (they never used self anyway).
As far as an end user goes the ComputeUncompute is used just the same way. As I changed things around a little bit though any developer that might have extended the base class, for some custom fidelity, would need to update their code for the _run. 
I kept the changes minimal though the presence of the _run is …
> Fix ComputeUncompute State Fidelity threading issue

- .github/workflows/main.yml
Changed windows-2019 to windows-latest (current same as windows-2022) so it running on a newer version and use latest like is done on others. My recollection of it using windows-2019 specifically was when Aer was being built from source. As this is no longer the case it seems better to switch to a newer version and do -latest like is done with Ubuntu and Mac
I already did this in Nature https://github.com/qiskit-community/qiskit-nature/pull/1266 as part of updating CI there.
The branch rules will need updating to account for the job name change.
> Update CI to use latest windows

- qiskit_algorithms/minimum_eigensolvers/diagonal_estimator.py
The primitives are being altered in Qiskit where Qiskit/qiskit#11051 removed attributes from the base classes which affected sub-classes using these. In such subclasses, the diagonal estimator in algorithms still there in Qiskit, corresponding private attributes were added to these. This mirrors the same change - it should be compatible with current Qiskit base estimator too as this same code is there in the constructor, so while its done twice now in the future this will be needed. Things may be further refactored for the primitives but this keeps things updated for now.
> Update Diagonal Estimator for Qiskit change

- requirements.txt
While doing the recent changes I did I noticed that requirements still is depending on `qiskit-terra` so this updates that and switches it to `qiskit`.
> Update requirements to `qiskit` instead of `qiskit-terra`

- .github/workflows/main.yml
Adds jobs (Ubuntu at min/max python supported versions - 3.8 and 3.11) which test Qiskit Algorithms against Qsikit main dev branch to give insight into into any breaking changes. Breaking changes are expected in Qiskit 1.0 so this will enable monitoring of the main dev branch to see if any failures occur that do not against the stable released version used elsewhere in the main tests here.
These new jobs will not be added to the branch rules but its expected that failures be investigated and action taken accordingly. Not all failures may be compatibility/breaking changes but may be due to the fact the Qiskit CI has occasional failures, say due to changes in dependents, but the reason can be uncovered by investigating the build output from the jobs etc.
As this is more to monitor things I …
> Add unit test jobs with Qiskit main

- qiskit_algorithms/utils/algorithm_globals.py
The algorithm_globals function here in Qiskit Algorithms delegates its behavior to the equivalent logic in Qiskit as part of the migration support from algorithms in Qiskit that were migrated here. Since that time the function in Qiskit has been deprecated and deprecation messages added to alert the user to the migration. When this logic here was initially done those deprecation messages were not present, but since that time the way the logic is here causes users to see these deprecation messages which they should not. These messages also flooded the combined deprecation output from CI here. This PR suppresses these around the points of usage here so the messages are no longer raised.
> Suppress qiskit algorithm globals deprecation messages

- .github/workflows/main.yml
- releasenotes/notes/py_3_12_support-13aa1a32494d25e7.yaml
- setup.py
Given Qiskit 0.45.1 just released with Python 3.12 support I have added that here to Algorithms. 
I added a new Ubuntu 3.12 run so that OS spans all the versions. I changed Mac and Windows to 3.12 from 3.11 so it tests the min and max versions supported now (just as it did before when 3.11 was the max). I did the same for Qiskit Main monitoring.
FYI I do not have 3.12 locally at present to check things so we'll see how it goes here...
> Add Python 3.12 support

- .github/workflows/main.yml
Ci fails some unit testing when using the latest Python 3.12.1 (CI just had 3.12 so pulls this in). This changes to explicitly use 3.12.0 to avoid the unit testing problem as per issue #113 I will leave #113 open so this pinning to 3.12.0 can be reverted once that is fixed.
> Run CI tests using Python 3.12.0

- README.md
- setup.py
Addresses first part of #124
Updates urls from ecosystem to new location
> Update setup, readme urls

- .github/workflows/main.yml
Qiskit Aer recently released 0.13.2 which now supports Python 3.12 so that wheels are available and it does not need to get built locally. This allows up to bump the Windows CI max Python version in which we test from 3.11 to 3.12 to be the same as Ubuntu and MacOS.
Resolves #109
While this changed to 3.12 it is actually specifically 3.12.0 (same as other platforms) until #113 is addressed (i.e. when an updated testtools is released).
This will require branch rules to be updated since the Required Win 3.11 job will no longer happen with this change. i.e.
- Algorithms (windows-latest, 3.11):   _Remove_
- Algorithms (windows-latest, 3.12.0):  _Make Required_
> Update Win CI max ver to 3.12 now Aer supports 3.12

- .pylintdict
- qiskit_algorithms/algorithm_job.py
Resolves #126
I chose to do this in a way that's compatible with the currently defined min Qiskit version and avoids deprecation warnings for future versions where in PrimitiveJob its now `_submit()`
I altered the text about `an empty class` its no longer true when looking at the source, and in the docs it not appear that way at all anyway since it showed all the inherited methods. I also added a note about the why submit() exists in it now and a TODO as a reminder to potentially revisit this in the future.
> Fix calling deprecated submit()

- qiskit_algorithms/optimizers/aqgd.py
- test/optimizers/test_optimizer_aqgd.py
#116 was done at the end of last year and the copyright dates passed through CI fine such that it merged. The merge run failed though https://github.com/qiskit-community/qiskit-algorithms/actions/runs/7658685508 due to the merge now being in 2024 and the files in main updated by merging the remote changes. This then led to failure of #128 when the branch was updated there.
This alters the dates to 2024 so CI will pass again.
> Fix dates from recent merge of #116

- docs/conf.py
- docs/tutorials/01_algorithms_introduction.ipynb
- docs/tutorials/02_vqe_advanced_options.ipynb
- docs/tutorials/04_vqd.ipynb
- docs/tutorials/05_qaoa.ipynb
- docs/tutorials/07_grover_examples.ipynb
- docs/tutorials/10_pvqd.ipynb
- docs/tutorials/11_VarQTE.ipynb
Updates links away from qiskit.org to the new locations for the docs
Fixes #135
#124 : I update all links but Aer for #124 as Aer is not yet done. This amounts to a couple of links in each of the 01 and 03 tutorials that will need to wait on relocated docs for Aer.
Now that all the applications and the algorithms docs are deployed on github pages this updates the intersphinx links, in conf.py, and also urls that are coded directly in other places such as the readme and tutorials.
Note that the current theme is still emitting a link to qiskit.org/ecosystem, but that will get redirected for now until such time as Qiskit/qiskit_sphinx_theme#588 is resolved and new docs are generated with such an updated theme and re-deployed.
> Update intersphinx links and others

- test/__init__.py
- test/decorators.py
- test/eigensolvers/test_vqd.py
- test/gradients/test_estimator_gradient.py
- test/minimum_eigensolvers/test_sampling_vqe.py
- test/minimum_eigensolvers/test_vqe.py
- test/optimizers/test_optimizer_aqgd.py
- test/time_evolvers/test_pvqd.py
`slow_test` used to be part of `qiskit.test` but the whole `test` folder was removed for Qiskit 1.0. This adds a copy of that slow_test decorator locally.
Additionally this updates other units testing for failures that started since this was created - see comments below for more detail.
The Monitor jobs, that run against Qiskit main branch, started failing last night after the removal.
> Add slow_test as it's no longer part of Qiskit 1.0

- .github/workflows/main.yml
Closes #113
It seems that the breaking change that caused test failure in 3.12.1, that had us pin to 3.12.0, has been reverted in 3.12.2. While the testtools has been fixed to accommodate that change, it has not yet had a release with the update in it, but given the change in Python has been reverted its no longer needed presently.
> Revert Python 3.12.0 specific usage

- qiskit_algorithms/eigensolvers/vqd.py
This PR replicates the changes done in https://github.com/Qiskit/qiskit/pull/12162 (See for information) to `qiskit/algorithms/eigensolvers/vqd.py` to fix the docs of two attributes (`optimizer` and `initial_point`)
> Fix bad indentation and missing hyphen on `vqd.py`

- qiskit_algorithms/gradients/reverse/derive_circuit.py
- test/test_amplitude_estimators.py
Qiskit tests against main have been failing lint recently due to power() in QuantumCircuit gaining an extra parameter. With 1.1 going live shortly, where it will become the stable version tested against here, this amends the test to work and pass lint for existing versions of Qiskit e.g 0.46 and 1.0 as well as 1.1
As it's just a test case fix there is no reno needed. I marked this for backporting to stable as it will affect any builds done there once 1.1 releases.
> Fix power() in subclass test for QuantumCircuit change

- .pylintdict
- qiskit_algorithms/amplitude_estimators/fae.py
- qiskit_algorithms/eigensolvers/vqd.py
- qiskit_algorithms/gradients/finite_diff/finite_diff_estimator_gradient.py
- qiskit_algorithms/time_evolvers/trotterization/trotter_qrte.py
- test/test_grover.py
- test/time_evolvers/test_trotter_qrte.py
Fixes to various possibly undefined errors from newest lint
```
************* Module qiskit_algorithms.gradients.finite_diff.finite_diff_estimator_gradient
qiskit_algorithms/gradients/finite_diff/finite_diff_estimator_gradient.py:144:29: E0606: Possibly using variable 'gradient' before assignment (possibly-used-before-assignment)
************* Module qiskit_algorithms.amplitude_estimators.fae
qiskit_algorithms/amplitude_estimators/fae.py:217:36: E0606: Possibly using variable 'v' before assignment (possibly-used-before-assignment)
************* Module qiskit_algorithms.eigensolvers.vqd
qiskit_algorithms/eigensolvers/vqd.py:286:23: E0606: Possibly using variable 'initial_point' before assignment (possibly-used-before-assignment)
************* Module …
```
> Fix lint errors for latest pylint

- .pylintdict
- qiskit_algorithms/eigensolvers/numpy_eigensolver.py
- releasenotes/notes/numpy_2.0_fix-c29681db4874eee8.yaml
Fixes #182
Scipy 1.14 compatibility fix
Using .H from csr_matrix had been deprecated and has now been removed in scipy 1.14. This changes NumPyEigensolver, to use an alternative (and works with the prior scipy). This also ends up fixing CI which has been failing in nightly builds recently.
> Scipy 1.14 compatibility fix

- .pylintdict
- qiskit_algorithms/optimizers/gradient_descent.py
Nightly CI has been failing recently with a couple of lint checks in consecutive lines. I surrounded the pair with a disable and enable for the specific error - one already has a mypy suppression and I was unable to add single line comments the same way with black reformatting things.
> Fixes so link check passes in CI for latest version

- qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
Nightly CI is failing following mypy 1.11 release. It seems that the detected error is now different. I changed things to be compatible with the prior version which ends up with two ignores and and unused ignore with each so that the other version does not raise the specific error does not raise another about it being unused.
What with all the suppression there now I can't help but think the code ought to be fixed in some way. But for now it works, i.e. passes unit tests etc. so this simply updates things for CI to pass too.
> Update ignore for latest mypy

- .github/workflows/main.yml
This changes CI so that the tests run against Qiskit main are now done on 3.9 as the minimum level (rather than 3.8). See also this issue, which this partially addresses
* #201
This only changes the CI done against Qiskit main branch as this change is not yet in a released version. These tests on main do not cause any PR to not be mergable as the intent was just to have jobs, particularly in nightly runs, where things were tested again Qiskit main in case of any breaking changes etc we would have an idea early on and could take whatever appropriate action was deemed right to sort out any failure(s). In this case the change was known to be happening so I have simply just amended CI here accordingly for its tests against Qiskit main.
> Change test with Qiskit main to 3.9 for min version

- qiskit_algorithms/optimizers/gradient_descent.py
Template is not really applicable, since it only updates docstrings ✅ 
Solving Issue described in: https://github.com/qiskit-community/qiskit-algorithms/issues/208
> Fix Docstring typo in GradientDescent

- docs/tutorials/04_vqd.ipynb
- qiskit_algorithms/eigensolvers/vqd.py
- test/eigensolvers/test_vqd.py
As mentioned [here](https://github.com/qiskit-community/qiskit-algorithms/issues/136#issuecomment-2356561939), some optimizers don't work well with shots-based samplers. This leads to VQD returning sometimes absurd values, as shown [here](https://github.com/qiskit-community/qiskit-algorithms/issues/136#issuecomment-2356242004).
This Pull Request adds a `convergence_threshold` to `VQD` to test whether the optimization converged well.
It also paves the road for adapting VQD to V2 primitives.
Changes that were made:
- a `convergence_threshold` parameter now tests whether the average fidelity of the $k$-th eigenstate w.r.t. the previously found eigenstates is larger than this threshold, indicating that not only the eigenvalue returned is likely to be false, but the next iterations won't make …
> Adding a convergence threshold to VQD to filter non-sensible values

- .github/workflows/main.yml
- pyproject.toml
- qiskit_algorithms/optimizers/gradient_descent.py
- qiskit_algorithms/optimizers/steppable_optimizer.py
- releasenotes/notes/add_python_3_13_support-3de8e3dc2e9dbd57.yaml
- setup.py
- tox.ini
Add support for Python 3.13
At present I expect this to failed in the same way https://github.com/qiskit-community/qiskit-machine-learning/pull/836 is currently in this equivalent test here that was copied to "test.optimizers.test_gradient_descent.TestGradientDescent.test_start" when it tests a couple of dataclass equalities. I have a fix that works for me locally, see this comment in the above PR https://github.com/qiskit-community/qiskit-machine-learning/pull/836#issuecomment-2722614189 but I just wanted to see it failing in CI too before applying it just to make sure.
---
Will need branch rules updating for this change once its ok/approved.
> Add Python 3.13 as supported

- .pylintdict
- qiskit_algorithms/optimizers/__init__.py
- qiskit_algorithms/optimizers/nlopts/nloptimizer.py
- qiskit_algorithms/optimizers/nlopts/sbplx.py
- releasenotes/notes/sbplx_optimizer-a27361fc4ac8de8c.yaml
- test/optimizers/test_optimizers.py
The SBPLX algorithm is an extension to Nelder-Mead and expected to yield better results.
Thus, it might be beneficial to add the interface to the NLopt implementation of SBPLX.
It might be beneficial to add other NLopt optimizers as well. Feel free to comment whether I should do that.
Closes #227
> Adds supports for SBPLX optimizer from nlopt

- docs/conf.py
- docs/getting_started.rst
- docs/tutorials/01_algorithms_introduction.ipynb
- docs/tutorials/02_vqe_advanced_options.ipynb
- docs/tutorials/03_vqe_simulation_with_noise.ipynb
- docs/tutorials/10_pvqd.ipynb
- docs/tutorials/12_gradients_framework.ipynb
- docs/tutorials/13_trotterQRTE.ipynb
- qiskit_algorithms/__init__.py
- releasenotes/notes/0.3/qiskit_1_0_compatible-405b357d032fbeeb.yaml
The documentation source of truth is moving to https://quantum.cloud.ibm.com/.
> Update intersphinx mapping and other URLs pointing to IQP Classic

- qiskit_algorithms/algorithm_job.py
- qiskit_algorithms/custom_types.py
- qiskit_algorithms/phase_estimators/phase_estimator.py
#197 passed CI checks and was merged but the CI action taken once the branch changes were merged to main failed as below,
```
Wrong Copyright Year:'qiskit_algorithms/custom_types.py':  Current:'# (C) Copyright IBM 2024.' Correct:'# (C) Copyright IBM 2024, 2025.'
Wrong Copyright Year:'qiskit_algorithms/phase_estimators/phase_estimator.py':  Current:'# (C) Copyright IBM 2020, 2024.' Correct:'# (C) Copyright IBM 2020, 2025.'
Wrong Copyright Year:'qiskit_algorithms/algorithm_job.py':  Current:'# (C) Copyright IBM 2022, 2024.' Correct:'# (C) Copyright IBM 2022, 2025.'
0 files have utf8 headers.
3 of 231 files with copyright header have wrong years.
```
This updates the copyright dates for those 3 files, which were last changed in 2024 before the merge commit. I think we have seen this in the …
> Update copyright dates following #197 merge

- qiskit_algorithms/optimizers/qnspsa.py
Fixes #163. As described there, the docstring for `QNSPSA` still used the `optimize` method instead of the `minimize` one. This PR corrects this.
> Fixed QNSPSA docstring

- qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
- releasenotes/notes/fix-adaptvqe-qiskit-2.1.2-8ca695d06e88e972.yaml
As per [this comment in #244](https://github.com/qiskit-community/qiskit-algorithms/issues/244#issuecomment-3241698362), https://github.com/Qiskit/qiskit/pull/14714 will only be merged in the `2.2.0` release of Qiskit. As such, Qiskit/qiskit#14567 is still a problem in the `2.1.2` release.
We thus need to `simplify` the `commutators` ourselves in `AdaptVQE` in this qiskit release. This was already done for the `2.1.0` and `2.1.2` releases. This PR adds the `2.1.2` release to the versions in which to perform this additional operation.
This would prevent users from encountering errors when running `AdaptVQE`.
Note: this doesn't preclude having to pin the qiskit version to be different than `2.1.2` in `requirements-dev.txt`, since Qiskit/qiskit#14611 is not fixed in the `2.1.2` release …
> Added 2.1.2 to caught versions of Qiskit in AdaptVQE

- releasenotes/notes/0.4/drop_python_3_8-dffbed172a8cccf1.yaml
- releasenotes/notes/0.4/numpy_2.0_fix-c29681db4874eee8.yaml
- releasenotes/notes/0.4/prelude_0.4_release-a9d23b9c63550bd2.yaml
- releasenotes/notes/0.4/raise-error-incorrect-bounds-passing-c878f155221fa8f4.yaml
- releasenotes/notes/0.4/replaced-v1-primitives-by-v2-ones-897d9610351bd54b.yaml
- releasenotes/notes/0.4/sampler_as_positional_arg_for_qnspsa-2efca170947f3cd7.yaml
This is a small follow-up fixing issues found in the recent docs deployment.
> Improve 0.4 release note prelude formatting
